query getActors($query: actors_bool_exp!) {
  actors(where: $query){
    first_name
    id
    last_name
    image {
      id
      url
    }
    movies_actors_aggregate {
      aggregate {
        count
      }
    }
  }
}