query getUser($id:uuid!) {
  users_by_pk(id: $id) {
    email
    firstName
    id
    lastName
    role
    image{
      id
      url
    }
    bookings {
      id
      movie {
        title
        image {
          url
        }
      }
    }
  }
}
