query filterByGenere($genere: String!) {
 movies(where: {movies_generes: {genere: {name: {_ilike: $genere}}}})
   {
    date
    director {
      first_name
      id
      last_name
      image {
        url
      }
    }
    image{
      id
      url
    }
    discrption
    duration
    id
    status
    title
    movies_generes {
      genere {
        name
        id
      }
    }
  }
}


























