query getMovies($query: movies_bool_exp) {
  movies(where: $query) {
    date
    director_id
    director {
      first_name
      id
      last_name
      image {
        url
      }
    }
    image{
      id
      url
    }
    discrption
    duration
    id
    title
    status
    movies_generes {
      genere {
        name
        id
      }
    }
    movies_actors {
      actor {
        first_name
        last_name
        id
      }
    }
    ratings_aggregate {
      aggregate {
        avg {
          rating
        }
      }
    }
  }
}
