query getActor($first_name: String!, $last_name: String!) {
  directors(where: {_or: [{first_name: {_ilike: $first_name}}, {last_name: {_ilike: $last_name}}]}){
     first_name
      id
      last_name
      image {
        id
        url
      } 
  }
}